services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-network
  app:
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - payment-network

networks:
  payment-network:

volumes:
  pgdata:
